# This manifest installs Nuage VRS on
# each worker node in a Kubernetes cluster.
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: nuage-vrs
  namespace: kube-system
  labels:
    k8s-app: nuage-vrs
spec:
  selector:
    matchLabels:
      k8s-app: nuage-vrs
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: nuage-vrs
    spec:
      hostNetwork: true
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
          operator: Exists
      containers:
        # This container installs Nuage VRS running as a
        # container on each worker node
        - name: nuage-vrs
          image: nuage/vrs:{{.VRSReleaseTag}}
          securityContext:
            privileged: true
          env:
            # Configure parameters for VRS openvswitch file
            - name: NUAGE_ACTIVE_CONTROLLER
              value: {{.ActiveController}}
            - name: NUAGE_STANDBY_CONTROLLER
              value: {{.StandbyController}}
            - name: NUAGE_PLATFORM
              value: {{.Platform}}
            - name: NUAGE_K8S_SERVICE_IPV4_SUBNET
              value: {{.ServiceNetworkCIDR}}
            - name: NUAGE_K8S_POD_NETWORK_CIDR
              value: {{.ClusterNetworkCIDR}}
            - name: NUAGE_NETWORK_UPLINK_INTF
              value: {{.UplinkInterface}}
          volumeMounts:
            - mountPath: /var/run
              name: vrs-run-dir
            - mountPath: /var/log
              name: vrs-log-dir
            - mountPath: /sys/module
              name: sys-mod-dir
              readOnly: true
            - mountPath: /lib/modules
              name: lib-mod-dir
              readOnly: true
      volumes:
        - name: vrs-run-dir
          hostPath:
            path: /var/run
        - name: vrs-log-dir
          hostPath:
            path: /var/log
        - name: sys-mod-dir
          hostPath:
            path: /sys/module
        - name: lib-mod-dir
          hostPath:
            path: /lib/modules
