# Copyright 2020 Nokia
# Licensed under the Apache License 2.0.
# SPDX-License-Identifier: Apache-2.0

# This manifest installs Nuage VRS on
# each worker node in a Kubernetes cluster.
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: nuage-vrs
  namespace: nuage-network-operator
  labels:
    k8s-app: nuage-vrs
spec:
  selector:
    matchLabels:
      k8s-app: nuage-vrs
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: nuage-vrs
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
      hostNetwork: true
      containers:
        # This container installs Nuage VRS running as a
        # container on each worker node
        - name: nuage-vrs
          image: "{{.ReleaseConfig.VRSTag}}"
          securityContext:
            privileged: true
          env:
            # Configure parameters for VRS openvswitch file
            - name: NUAGE_ACTIVE_CONTROLLER
              value: "{{index .VRSConfig.Controllers 0}}"
              {{if (eq (len .VRSConfig.Controllers) 2)}}
            - name: NUAGE_STANDBY_CONTROLLER
              value: "{{index .VRSConfig.Controllers 1}}"
              {{end}}
            - name: NUAGE_PLATFORM
              value: "\"{{.VRSConfig.Platform}}\""
            - name: NUAGE_K8S_SERVICE_IPV4_SUBNET
              value: "{{addEscapeChar .ClusterNetworkConfig.ServiceNetworkCIDR}}"
            - name: NUAGE_K8S_POD_NETWORK_CIDR
              value: "{{addEscapeChar .ClusterNetworkConfig.ClusterNetworkCIDR}}"
            - name: NUAGE_NETWORK_UPLINK_INTF
              value: "{{.VRSConfig.UnderlayUplink}}"
          volumeMounts:
            - mountPath: /var/run
              name: vrs-run-dir
            - mountPath: /var/log
              name: vrs-log-dir
            - mountPath: /sys/module
              name: sys-mod-dir
              readOnly: true
            - mountPath: /lib/modules
              name: lib-mod-dir
              readOnly: true
      volumes:
        - name: vrs-run-dir
          hostPath:
            path: /var/run
        - name: vrs-log-dir
          hostPath:
            path: /var/log
        - name: sys-mod-dir
          hostPath:
            path: /sys/module
        - name: lib-mod-dir
          hostPath:
            path: /lib/modules
