apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: nuage-cni
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
  - nonResourceURLs:
  - '*'
  verbs:
  - '*'
