# Copyright 2020 Nokia
# Licensed under the Apache License 2.0.
# SPDX-License-Identifier: Apache-2.0



# permissions for end users to edit nuagecniconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nuagecniconfig-editor-role
rules:
- apiGroups:
  - operator.nuage.io
  resources:
  - nuagecniconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.nuage.io
  resources:
  - nuagecniconfigs/status
  verbs:
  - get
