apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: networks.operator.nuage.io
spec:
  group: operator.nuage.io
  names:
    kind: Network
    listKind: NetworkList
    plural: networks
    singular: network
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            cniConfig:
              properties:
                clusterRoleBindingName:
                  type: string
                clusterRoleName:
                  type: string
                cniVersion:
                  type: string
                kubeConfig:
                  type: string
                logFileSize:
                  format: int64
                  type: integer
                logLevel:
                  type: string
                monitorInterval:
                  format: int64
                  type: integer
                mtu:
                  format: int64
                  type: integer
                nuageMonitorURL:
                  type: string
                nuageSiteID:
                  format: int64
                  type: integer
                portResolveTimer:
                  format: int64
                  type: integer
                serviceAccountName:
                  type: string
                staleEntryTimeout:
                  format: int64
                  type: integer
                vrsBridge:
                  type: string
                vrsConnectionCheckTimer:
                  format: int64
                  type: integer
                vrsEndpoint:
                  type: string
              type: object
            monitorConfig:
              properties:
                ClusterRoleBindingName:
                  type: string
                ClusterRoleName:
                  type: string
                ServiceAccountName:
                  type: string
                restServerAddress:
                  type: string
                restServerPort:
                  format: int64
                  type: integer
                vsdAddress:
                  minLength: 1
                  type: string
                vsdFlags:
                  properties:
                    autoScaleSubnets:
                      type: boolean
                    statsEnabled:
                      type: boolean
                    underlayEnabled:
                      type: boolean
                  type: object
                vsdMetadata:
                  properties:
                    domain:
                      minLength: 1
                      type: string
                    enterprise:
                      minLength: 1
                      type: string
                    user:
                      minLength: 1
                      type: string
                    userCert:
                      minLength: 1
                      type: string
                    userKey:
                      minLength: 1
                      type: string
                  required:
                  - enterprise
                  - domain
                  - user
                  - userCert
                  - userKey
                  type: object
                vsdPort:
                  format: int64
                  minimum: 0
                  type: integer
              required:
              - vsdAddress
              - vsdPort
              - vsdMetadata
              - vsdFlags
              type: object
            releaseConfig:
              properties:
                cniTag:
                  minLength: 1
                  type: string
                monitorTag:
                  minLength: 1
                  type: string
                registry:
                  properties:
                    password:
                      minLength: 1
                      type: string
                    url:
                      minLength: 1
                      type: string
                    username:
                      minLength: 1
                      type: string
                  required:
                  - url
                  - username
                  - password
                  type: object
                vrsTag:
                  minLength: 1
                  type: string
              required:
              - registry
              - vrsTag
              - cniTag
              - monitorTag
              type: object
            vrsConfig:
              properties:
                controllers:
                  items:
                    type: string
                  minItems: 1
                  type: array
                platform:
                  type: string
                underlayUplink:
                  minLength: 1
                  type: string
              required:
              - controllers
              - underlayUplink
              type: object
          required:
          - vrsConfig
          - cniConfig
          - monitorConfig
          - releaseConfig
          type: object
        status:
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
