apiVersion: operator.nuage.io/v1alpha1
kind: NuageCNIConfig
metadata:
  name: nuage-network
spec:
  vrsConfig:
     controllers:
        - 10.40.1.111
     underlayUplink: eth0
  monitorConfig:
     vsdAddress: 10.40.1.82
     vsdPort: 7443
     vsdMetadata:
        enterprise: centos-operator
        domain: centos-operator-1-14
        user: k8s-admin
        userCert: |
         -----BEGIN CERTIFICATE-----
         MIIEPTCCAyWgAwIBAgIISY7N4HQIzS0wDQYJKoZIhvcNAQELBQAwEDEOMAwGA1UE
         AwwFVlNQQ0EwHhcNMjAwMTE0MTgyMTAxWhcNMjIwMTEzMTgyMTAxWjAuMRIwEAYD
         VQQDDAlrOHMtYWRtaW4xGDAWBgNVBAoMD2NlbnRvcy1vcGVyYXRvcjCCASIwDQYJ
         KoZIhvcNAQEBBQADggEPADCCAQoCggEBAK0wSQBwVPbeMRcBaZLCR3cg77UEPzqL
         4Y8UQjrmoZscXz+s3XUQOOhce4vhZwXwj/mr7IzOBQN2o3vdvu6UpfIDuEqaL3I5
         6YMjNgg3XaTHnt2oIpDkroiwI7N6YYcAKiICWQLt2qBE5UD5e8gj/k4fh0IQrLhm
         nF6RAywJWpoV2bpHtTUX1b6Dm3D4MoPSBdzAVx+9LKcFP3L23LmRJvYpADVEyodv
         R0hKTkUz/b6UPWGObqUmE8LTNFSmeu5zUIi2IbF9h35/QXYQh6LZp3bCN+Fvjt6X
         jR/W2BohFIfvvAd425kdYTuPdu1hhwkZ/3PP+xY8HxXcxJSmnYXOoxcCAwEAAaOC
         AXswggF3MAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUbpahSWiCHWit8ZZ9vlHX
         uoa/8L8wZAYIKwYBBQUHAQEEWDBWMFQGCCsGAQUFBzABhkhodHRwOi8vaG9zdC00
         MC0xLTgyLm5vYzMub3BlbnN0YWNrbG9jYWw6NzA4MC9lamJjYS9wdWJsaWN3ZWIv
         c3RhdHVzL29jc3AwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMEMIGRBgNV
         HR8EgYkwgYYwgYOga6BphmdodHRwOi8vaG9zdC00MC0xLTgyLm5vYzMub3BlbnN0
         YWNrbG9jYWw6NzA4MC9lamJjYS9wdWJsaWN3ZWIvd2ViZGlzdC9jZXJ0ZGlzdD9j
         bWQ9Y3JsJmlzc3Vlcj1DTiUzRFZTUENBohSkEjAQMQ4wDAYDVQQDDAVWU1BDQTAd
         BgNVHQ4EFgQUcUytN5/JXj5rrERrltwWX7Kjz50wDgYDVR0PAQH/BAQDAgXgMA0G
         CSqGSIb3DQEBCwUAA4IBAQCy1Iq0X+DafplKzsUlD4+qKgTsCseIQiAVboiAAo1i
         Ga2mZfyMKDykRDyql9eRUxXmsJqUIBZoGmrlViwFUVitSHz0udzPWmsm7OEzjJjL
         8hhyvllcUIUyl6WOC7n+3GFpUaMwLwYK3i2NsaFS+ldVEnQBsRutCK8TgUQzrRh0
         LO7cbQERhWIbuA11saIHixVJbC57sofyW7dV25n99oWXvfHRZ2hNiRny/DcbBR8K
         0sAy+W3freX7HDAIy7PYC1IE0wjqfsg2QAJabNNPx6QoWqki2/iS6E3RAcZfR/Jo
         gvVK65sFKIH+9sXiMe1opEjDCDtjLxy4x046ci1pv3IG
         -----END CERTIFICATE-----
        userKey: |
         -----BEGIN PRIVATE KEY-----
         MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCtMEkAcFT23jEX
         AWmSwkd3IO+1BD86i+GPFEI65qGbHF8/rN11EDjoXHuL4WcF8I/5q+yMzgUDdqN7
         3b7ulKXyA7hKmi9yOemDIzYIN12kx57dqCKQ5K6IsCOzemGHACoiAlkC7dqgROVA
         +XvII/5OH4dCEKy4ZpxekQMsCVqaFdm6R7U1F9W+g5tw+DKD0gXcwFcfvSynBT9y
         9ty5kSb2KQA1RMqHb0dISk5FM/2+lD1hjm6lJhPC0zRUpnruc1CItiGxfYd+f0F2
         EIei2ad2wjfhb47el40f1tgaIRSH77wHeNuZHWE7j3btYYcJGf9zz/sWPB8V3MSU
         pp2FzqMXAgMBAAECggEASJkFAPoVo6ZgTZR5/NsTugxEb0zodFJOqvuDB83F0I+E
         Hd0IuBmkwUKDR4+k8Ah3UeGPtzZlQ55nyXSapMgLB/gnOJ6JZQiBqkcIT0lmJ7zG
         C4R/eN1jjEjJrmKOn1iiUL9LML8j9irrLuFl0e/Emlr9B+SVgncA9WM0QTFqmUv+
         KBdY2AxVTyspESStTlkZQySK8lvs+GTrJyetznIUuwKG9Qa39QgghDguwzDqvCqW
         7qMnIUp0Ry469mlnhOGN/YziOJ7+w/f8sGN1Bkv36NG9q1cg1xdRd9BkwS2Kzo1h
         du5wzU8xtdMJ3a2rjK5rkrlG5F9fEBfmgmrYlf0wAQKBgQDoOzI4aUA1wTExCTdq
         kFStOvDt5SiAUC0WB+czYmyNflkf30nTb4jjUHLlVUqVMspbAAxnxAqOWljoIs36
         Q6YrcLIEPBJbZQFrFgKiowyFNS5sYEm+MadxhSEXEul/o3FfkANXLdaqWRT6TaqO
         oWVTp8zN6TlAdlajYOTJecTigQKBgQC+6hWgu/1fBmmZG2+vxOle7d7JLuMax7GD
         NhryV0sJd5hk0BzWoTe+85XtrUSs3Bo4Bp0b3FJWRzSmNMl2i2gHuuDH+YHqUe+9
         2F/Y+wVcNduZb1xFb28PFperGKPdF47DAV/5pitwUJ35j4rAZayxJ10kQHwNvixP
         xgJI7naJlwKBgCXAqdNd2OBkPbj5BJdAS2O190DVRhZF8m5obn99+qOt7JMv23KR
         6TD6/RKnIO7MSPUuNtYPmp+1tEpYjh+nK7ZYJbhmg51z+B0OgPMrineFQ7y+kn5m
         2A+uUsjLfEYRrfaZFNHxU7pxrOVcBuQU/MHyv2qiBXqjQkZhFBBkyUsBAoGAfUkg
         6Fp16+ZJZjCbGr4eaC2yBlS+tNRXqcPX6zFeDNhvKblpM3CZJLa1rUQHzWijzCCK
         +b2cSwJviqMZkrHpkykQWitjFmKu8ecM/1e8LMcrVYW/B9IZD83DuoRxBKZxCYfd
         c/eYihxdj2ijpZ8TtS4f8apfvqUOb0uCNFpJcAECgYBRifPVmkaE6lkGLW9vd3v1
         G7HmkVjZwiWzChYlOTw83YVMwGIx7QkXCa4JJDjkG2VYW9UwE/SRbWqZ3fbyhkG2
         AFubYB6oACYvZx5k7KlHzMWcC0tDSTi5IYtqSdm2C5lFxhkP59zE9dZIsGvkVvtc
         6NXUgVyAFVdbTFzZqYOP6g==
         -----END PRIVATE KEY-----
     vsdFlags:
        underlayEnabled: false
  releaseConfig:
     registry:
        url: 10.40.1.91
        username: username
        password: password
     vrsTag: nuage/vrs:6.0.4-111
     cniTag: registry.philippe.plm.nuagedemo.net/nuage/cni:latest
     monitorTag: registry.philippe.plm.nuagedemo.net/nuage/monitor:latest
     infraTag: registry.philippe.plm.nuagedemo.net/nuage/infra:latest
  cniConfig:
     mtu: 1450
     loadBalancerURL: https://10.40.1.91:9443
  podNetworkConfig:
     podNetwork: 70.70.0.0/16
     subnetLength: 8
     ClusterServiceNetworkCIDR: 10.96.0.0/12
