# Copyright 2020 Nokia
# Licensed under the Apache License 2.0.
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{.MonitorConfig.ServiceAccountName}}"
  namespace: nuage-network-operator
