# This ConfigMap is used to configure Nuage VSP configuration on master nodes
kind: ConfigMap
apiVersion: v1
metadata:
  name: nuage-monitor-config-data
  namespace: kube-system
data:
  # This will generate the required Nuage monitor configuration
  # on master nodes
  monitor_yaml_config: |
      {{with .KubeConfig}}
      kubeConfig: /usr/share/vsp-k8s/nuage.kubeconfig
      {{end}}
      # cluster network config
      masterConfig: /usr/share/nuage-openshift-monitor/net-config.yaml
      # Cluster Network CIDR
      clusterNetworkCIDR: {{.ClusterNetworkConfig.ClusterNetworkCIDR}}
      # Service Network CIDR
      serviceNetworkCIDR: {{.ClusterNetworkConfig.ServiceNetworkCIDR}}
      # URL of the VSD Architect
      vsdApiUrl: https://{{.MonitorConfig.VSDAddress}}/{{.MonitorConfig.VSDPort}}
      # API version to query against
      vspVersion: v5_0
      # Name of the enterprise in which pods will reside
      enterpriseName: {{.MonitorConfig.VSDMetadata.Enterprise}}
      # Name of the domain in which pods will reside
      domainName: {{.MonitorConfig.VSDMetadata.Domain}}
      # Enable/Disable encryption flags on VSD
      encryptionEnabled: {{.MonitorConfig.VSDFlags.EncryptionEnabled}}
      # Enable Underlay Support for this domain on VSD. 1 => enabled, 0 => disabled(default)
      underlaySupport: {{.MonitorConfig.VSDFlags.UnderlayEnabled}}
      # Enable Stats Logging for this domain on VSD. 1 => enabled, 0 => disabled(default)
      statsLogging: {{.MonitorConfig.VSDFlags.StatsEnabled}}
      # VSD generated user certificate file location on master node
      userCertificateFile: {{.MonitorConfig.VSDMetadata.UserCert}}
      # VSD generated user key file location on master node
      userKeyFile: {{.MonitorConfig.VSDMetadata.UserKey}}
      # Location where logs should be saved
      log_dir: /var/log/nuagekubemon/
      # Monitor rest server paramters
      # Logging level for the nuage monitor
      # allowed options are: 0 => INFO, 1 => WARNING, 2 => ERROR, 3 => FATAL
      logLevel: 0
      # Parameters related to the nuage monitor REST server
      nuageMonServer:
          URL: {{.MonitorConfig.MonitorAddress}}
          certificateDirectory: {{.MonitorConfig.CertificateDir}}
          clientCA: {{.Certificates.CA}}
          serverCertificate: {{.Certificates.Certificate}}
          serverKey: {{.Certificates.PrivateKey}}
      # etcd config required for HA
      etcdClientConfig:
          ca: ""
          certFile: ""
          keyFile: ""
          urls:
            - https://127.0.0.1:2379
      # auto scale subnets feature
      # 0 => disabled(default)
      # 1 => enabled
      autoScaleSubnets: {{.MonitorConfig.AutoScaleSubnets}}

  # This will generate the required Nuage network configuration
  # on master nodes
  net_yaml_config: |
      networkConfig:
        clusterNetworks:
          # hostSubnetLength is the size of the subnets
          # created on VSD
          - cidr: {{.ClusterNetworkConfig.ClusterNetworkCIDR}}
            hostSubnetLength: {{.ClusterNetworkConfig.ClusterNetworkSubnetLength}}
        serviceNetworkCIDR: {{.ClusterNetworkConfig.ServiceNetworkCIDR}}

---

# This manifest installs Nuage master node configuration on
# each Nuage master node in a cluster.
kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: nuage-monitor
  namespace: kube-system
  labels:
    k8s-app: nuage-monitor
spec:
  selector:
    matchLabels:
      k8s-app: nuage-monitor
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: nuage-monitor
    spec:
      hostNetwork: true
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
          operator: Exists
      nodeSelector:
        install-monitor: "true"
      serviceAccoutName: {{.MonitorConfig.ServiceAccountName}}
      containers:
        # This container configures Nuage Master node
        - name: nuage-monitor
          image: nuage/master:{{.ReleaseConfig.MonitorReleaseTag}}
          ports:
            - containerPort: 9443
              hostPort: 9443
          command: ["/configure-master.sh"]
          args: ["ose"]
          securityContext:
            privileged: true
          env:
            # Set the hostname based on the k8s node name.
            - name: KUBERNETES_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            # nuagekubemon.yaml config to install on each master node.
            - name: NUAGE_MASTER_VSP_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: nuage-monitor-config-data
                  key: monitor_yaml_config
            # net-config.yaml config to install on each master node.
            - name: NUAGE_MASTER_NETWORK_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: nuage-monitor-config-data
                  key: net_yaml_config
          volumeMounts:
            - mountPath: /var/log
              name: cni-log-dir
            - mountPath: /usr/share
              name: usr-share-dir
            - mountPath: /etc/kubernetes/pki/
              name: kubernetes-cert-dir
      volumes:
        - name: cni-log-dir
          hostPath:
            path: /var/log
        - name: usr-share-dir
          hostPath:
            path: /usr/share
        - name: kubernetes-cert-dir
          hostPath:
            path: /etc/kubernetes/pki/
